const data = {
    product: [
        {
            _id: '1',
            name: 'Green T-Shirt',
            category: 'T-shirt',
            image:'/images/1.jpg',
            price: 90000,
            countInStock:2,
            brand: 'Oblong',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality products',
        },
        {
            _id: '2',
            name: 'Yellow T-Shirt',
            category: 'T-shirt',
            image:'/images/2.jpg',
            price: 90000,
            countInStock:10,
            brand: 'Oblong',
            rating: 3.5,
            numReviews: 10,
            description: 'High quality products',
        },
        {
            _id: '3',
            name: 'Blue T-Shirt',
            category: 'T-shirt',
            image:'/images/3.jpg',
            price: 90000,
            countInStock:10,
            brand: 'Oblong',
            rating: 3,
            numReviews: 10,
            description: 'High quality products',
        },
        {
            _id: '4',
            name: 'Black T-Shirt',
            category: 'T-shirt',
            image:'/images/4.jpg',
            price: 90000,
            countInStock:10,
            brand: 'Oblong',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality products',
        },
        {
            _id: '5',
            name: 'Red T-Shirt',
            category: 'T-shirt',
            image:'/images/5.jpg',
            price: 90000,
            countInStock:0,
            brand: 'Oblong',
            rating: 5,
            numReviews: 10,
            description: 'High quality products',
        },
    ]
}
export default data;